[package]
name = "snn-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num = "0.4.1"
crossbeam = "0.8.2"
num_cpus = "1.16.0"
gag = "1.0.0"
dirs = "5.0.1"
chrono = "0.4.31"